# Generated by Django 4.2 on 2023-04-05 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="summary",
            field=models.TextField(default="First Product"),
        ),
    ]
