# Generated by Django 4.2 on 2023-04-07 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_product_summary"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name="product",
            name="summary",
            field=models.TextField(default="enter the summary"),
        ),
    ]
